Lets try to build the FPGA bit stream.

diff --git a/.github/workflows/fpga.yml b/.github/workflows/fpga.yml
--- a/.github/workflows/fpga.yml
+++ b/.github/workflows/fpga.yml
@@ -272,78 +272,68 @@ jobs:
   #         name: caliptra-fpga-kmod${{ inputs.artifact-suffix }}
   #         path: /tmp/caliptra-fpga-kmod/
   #         retention-days: 1
-  carl-test:
-    runs-on: [e2-standard-2]
+
+  build_bitstream:
+    runs-on: [e2-standard-8, fpga-tools]
+    timeout-minutes: 180
+
     steps:
       - name: Checkout repo
         uses: actions/checkout@v3
         with:
           submodules: 'true'
-      - name: Hello
+
+      - name: Mount FPGA tools
         run: |
-          echo "Hello world"
+          # This is an installation of Vivado 22.2 with support for Zynq Ultrascale+
+          sudo mkdir /fpga-tools
+          sudo mount UUID=be18f242-fb8d-4d99-971e-a8ae390ad620 /fpga-tools/
 
-  # build_bitstream:
-  #   runs-on: [e2-standard-8, fpga-tools]
-  #   timeout-minutes: 180
-  #
-  #   steps:
-  #     - name: Checkout repo
-  #       uses: actions/checkout@v3
-  #       with:
-  #         submodules: 'true'
-  #
-  #     - name: Mount FPGA tools
-  #       run: |
-  #         # This is an installation of Vivado 22.2 with support for Zynq Ultrascale+
-  #         sudo mkdir /fpga-tools
-  #         sudo mount UUID=be18f242-fb8d-4d99-971e-a8ae390ad620 /fpga-tools/
-  #
-  #     - name: Build FPGA bitstream
-  #       run: |
-  #         cd hw/fpga
-  #         mkdir caliptra_build
-  #         if [ "${{ inputs.fpga-itrng }}" == "false" ]; then
-  #           ITRNG=FALSE
-  #         else
-  #           ITRNG=TRUE
-  #         fi
-  #         if [ "${{ inputs.workflow_call }}" ]; then
-  #           RTL_VERSION="${{ inputs.hw-version }}"
-  #         else
-  #           RTL_VERSION="latest"
-  #         fi
-  #         /fpga-tools/Xilinx/Vivado/2022.2/bin/vivado -mode batch -source fpga_configuration.tcl -tclargs BUILD=TRUE ITRNG=${ITRNG} RTL_VERSION=${RTL_VERSION}
-  #         if [ ! -f caliptra_build/caliptra_fpga.bin ]; then
-  #           echo "Output file was not found; failing script"
-  #           exit 1
-  #         fi
-  #
-  #     - name: 'Upload FPGA bitstream artifact'
-  #       uses: actions/upload-artifact@v4
-  #       with:
-  #         name: caliptra-fpga-bitstream${{ inputs.artifact-suffix }}
-  #         path: hw/fpga/caliptra_build/caliptra_fpga.bin
+      - name: Build FPGA bitstream
+        run: |
+          cd hw/fpga
+          mkdir caliptra_build
+          if [ "${{ inputs.fpga-itrng }}" == "false" ]; then
+            ITRNG=FALSE
+          else
+            ITRNG=TRUE
+          fi
+          if [ "${{ inputs.workflow_call }}" ]; then
+            RTL_VERSION="${{ inputs.hw-version }}"
+          else
+            RTL_VERSION="latest"
+          fi
+          /fpga-tools/Xilinx/Vivado/2022.2/bin/vivado -mode batch -source fpga_configuration.tcl -tclargs BUILD=TRUE ITRNG=${ITRNG} RTL_VERSION=${RTL_VERSION}
+          if [ ! -f caliptra_build/caliptra_fpga.bin ]; then
+            echo "Output file was not found; failing script"
+            exit 1
+          fi
 
-  # cache_fpga_bitstream_artifact:
-  #   runs-on: ubuntu-22.04
-  #
-  #   # If we write to the cache from the self-hosted runner, the result is
-  #   # usually not accessible from GitHub-hosted runners. So cache the artifact
-  #   # instead.
-  #
-  #   steps:
-  #     - name: 'Download FPGA Bitstream Artifact'
-  #       uses: actions/download-artifact@v4
-  #       with:
-  #         name: caliptra-fpga-bitstream${{ inputs.artifact-suffix }}
-  #         path: /tmp/caliptra-fpga-bitstream
-  #
-  #     - name: Save FPGA bitstream to cache
-  #       uses: actions/cache/save@v3
-  #       with:
-  #         path: /tmp/caliptra-fpga-bitstream/caliptra_fpga.bin
-  #         key: ${{ needs.check_cache.outputs.rtl_cache_key }}
+      - name: 'Upload FPGA bitstream artifact'
+        uses: actions/upload-artifact@v4
+        with:
+          name: caliptra-fpga-bitstream${{ inputs.artifact-suffix }}
+          path: hw/fpga/caliptra_build/caliptra_fpga.bin
+
+  cache_fpga_bitstream_artifact:
+    runs-on: ubuntu-22.04
+
+    # If we write to the cache from the self-hosted runner, the result is
+    # usually not accessible from GitHub-hosted runners. So cache the artifact
+    # instead.
+
+    steps:
+      - name: 'Download FPGA Bitstream Artifact'
+        uses: actions/download-artifact@v4
+        with:
+          name: caliptra-fpga-bitstream${{ inputs.artifact-suffix }}
+          path: /tmp/caliptra-fpga-bitstream
+
+      - name: Save FPGA bitstream to cache
+        uses: actions/cache/save@v3
+        with:
+          path: /tmp/caliptra-fpga-bitstream/caliptra_fpga.bin
+          key: ${{ needs.check_cache.outputs.rtl_cache_key }}
 
   # test_artifacts:
   #   runs-on: caliptra-fpga
